require("user.options")
require("user.autocommands")
require("user.maps")
require("user.plugins")
require("user.gits")
require("user.lsp")
require("user.cmp")
require("user.surround")
require("user.illuminate")
require("user.treesitter")
require("user.autopairs")

