#!/usr/bin/env sh

spacebar -m config position           top
spacebar -m config height             24 
spacebar -m config text_font         "Fira Code:Regular:13.0"
spacebar -m config icon_font         "Font Awesome 5 Free:Regular:13.0"
spacebar -m config background_color  0xff202020
spacebar -m config foreground_color  0xffF5EEEE
spacebar -m config space_icon_strip  I II III IV V VI VII VIII IX X
spacebar -m config space_icon_strip            
spacebar -m config power_icon_strip   
spacebar -m config space_icon        
spacebar -m config clock_icon        
spacebar -m config clock_format      "%R %Y/%m/%d"

echo "spacebar configuration loaded.."
