#!/usr/bin/env bash
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"


# ====== Variables =============================

gaps_top="0"
gaps_bottom="0"
gaps_left="0"
gaps_right="0"
gaps_inner="6"


# ====== Tiling settings =======================

yabai -m config layout                      bsp

yabai -m config top_padding                 "${gaps_top}"
yabai -m config bottom_padding              "${gaps_bottom}"
yabai -m config left_padding                "${gaps_left}"
yabai -m config right_padding               "${gaps_right}"
yabai -m config window_gap                  "${gaps_inner}"

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

yabai -m config window_topmost              off
yabai -m config window_opacity              on
yabai -m config window_shadow               float

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       1.0
yabai -m config split_ratio                 0.5
yabai -m config auto_balance                off
# named tabs
yabai -m space 1 --label web
yabai -m space 2 --label code
yabai -m space 3 --label term
yabai -m space 4 --label plan

# ====== Border settings =======================

yabai -m config window_border               off
yabai -m config window_border_width         6
yabai -m config active_window_border_color   0xffc2808a
yabai -m config normal_window_border_color   0xff88779b


# ====== Spacebar settings =======================
yabai -m config external_bar all:0:24
# ====== List of rules =========================

yabai -m rule --add app!="Alacritty|Logseq|石墨文档|Safari|GoLand|Google Chrome|Firefox|Brave Browser|iTerm2|Sublime Text" manage=off border=off
yabai -m signal --add event=window_created app="^PyCharm|GoLand$" action='/Users/lin/configuration/yabai/s_float.sh'

