#!/usr/bin/env bash
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"


# ====== Variables =============================

gaps_top="10"
gaps_bottom="10"
gaps_left="10"
gaps_right="10"
gaps_inner="12"
# active_border_color=FFD662
# deactive_border_color=234E70


# ====== Tiling settings =======================

yabai -m config \
	layout                      bsp \
	top_padding                 "${gaps_top}" \
	bottom_padding              "${gaps_bottom}" \
	left_padding                "${gaps_left}" \
	right_padding               "${gaps_right}" \
	window_gap                  "${gaps_inner}" \
	mouse_follows_focus         off \
	focus_follows_mouse         off \
	mouse_modifier              fn \
	mouse_action1               move \
	mouse_action2               resize \
	window_opacity              on \
	window_shadow               float \
	active_window_opacity       1.0 \
	normal_window_opacity       1.0 \
	split_ratio                 0.5 \
	auto_balance                off \
	external_bar all:0:0;


yabai -m space 1 --label web
yabai -m space 2 --label code
yabai -m space 3 --label term
yabai -m space 4 --label plan

yabai -m rule --add app!="Code|Vivaldi|Safari浏览器|Tor Browser|DataGrip|Microsoft Edge|Alacritty|Logseq|GoLand|Google Chrome|Firefox|Brave Browser|iTerm2" manage=off # border=off
yabai -m rule --add app="Sublime Text" manage=off grid="6:5:1:1:3:4" # border=on 
yabai -m rule --add app="kitty" manage=off grid="6:5:1:1:3:4" opacity=0.9 # border=on 

# todo rebalance kitty when switching space
yabai -m signal --add event=window_created app="DataGrip|PyCharm|GoLand" action='/Users/lin/configuration/yabai/s_float.sh'

yabai -m rule --add app!="asldkxz" sub-layer="normal"
# https://github.com/FelixKratz/JankyBorders
# active_border_color=FFD662
# deactive_border_color=234E70
borders active_color=0xffFFD662 inactive_color=0xff234E70 width=8.0 &
echo "yabai configuration loaded.."
